[tool.poetry]
name = "goph420_lab03"
version = "0.1.0"
description = "GOPH 420/699 – Inv. and Param. Est. for Geoph. (W2025) Lab Assignment #3"
authors = ["Khalid Abdulrahman"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
matplotlib = "*"


